version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: assistant-gateway
    ports:
      - "8555:8000"
    restart: unless-stopped
    depends_on:
      - orpheus_service
      - voxtral_service
    environment:
      - ORPHEUS_URL=http://orpheus_service:8001
      - VOXTRAL_URL=http://voxtral_service:8002

  orpheus_service:
    build: ./orpheus_service
    container_name: orpheus-service
    ipc: host
    # This is the corrected syntax for GPU access with Podman
    devices:
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - orpheus_cache:/root/.cache
    restart: unless-stopped

  voxtral_service:
    build: ./voxtral_service
    container_name: voxtral-service
    ipc: host
    # This is the corrected syntax for GPU access with Podman
    devices:
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - voxtral_cache:/root/.cache
    restart: unless-stopped

volumes:
  orpheus_cache:
  voxtral_cache:
