version: '3.8'

services:
  # 1. The Gateway Service (Client-Facing)
  gateway:
    build: ./gateway
    container_name: assistant-gateway
    ports:
      - "8555:8000"
    restart: unless-stopped
    depends_on:
      - orpheus_service
      - voxtral_service
    environment:
      - ORPHEUS_URL=http://orpheus_service:8001
      - VOXTRAL_URL=http://voxtral_service:8002

  # 2. The Orpheus TTS Service (GPU-Powered)
  orpheus_service:
    build: ./orpheus_service
    container_name: orpheus-service
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - orpheus_cache:/root/.cache
    restart: unless-stopped

  # 3. The Voxtral ASR Service (GPU-Powered)
  voxtral_service:
    build: ./voxtral_service
    container_name: voxtral-service
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - voxtral_cache:/root/.cache
    restart: unless-stopped

volumes:
  orpheus_cache:
  voxtral_cache:
